# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy necessary files
COPY pyproject.toml requirements.txt ./
COPY mcp_doc_scraper ./mcp_doc_scraper

# Install dependencies and install the package in editable mode
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir -e .

CMD ["python", "-m", "mcp_doc_scraper"]
